on:
  push:
    # TODO: Figure out how to limit tags to things that look like semver
    # (maybe it's not something we care about?)
    tags: ["v*"]

jobs:
  Publish:
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      # We're getting tags from GitHub, so this is irrelevant
      - run: nix develop .#deploy -c npm version --no-git-tag-version "$TAG"
        env:
          TAG: ${{ github.ref_name }}
      - run: nix develop .#deploy -c npm ci
      - run: nix develop .#deploy -c npm publish --verbose --access public
