name: Publish CSS release

on:
  push:
    branches: [main]

jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # In order to upload artifacts to GitHub releases
      id-token: write # In order to request a JWT for AWS auth
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/determinate-nix-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main
      - run: nix develop -c npm ci
      - run: nix develop -c npm run build

      # Publish minified CSS at:
      # https://github.com/DeterminateSystems/ui/releases/latest/download/index.min.css
      - uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          tag_name: latest
          draft: false # make available as latest
          files: |
            lib/index.min.css
